compilerdkfjahösldkjfalsefaclsdkjföasldfj
compilerdkfjaösldkjfflsdkjföasldfj
compilerdkfjafgösldkjfeflsacjtzfghhdkjföasldfj

###Compile

./isis.o: ./../.../../isis.cpp ./../.../../isis.hpp
		./../.../../isgnjzis.cpp
		./../.../../isfsdfas.cpp
		./../.../../idsfsis.cpp
		./../.../../isisdfs.cpp
	$(CXX) ./../../../../../src/isis.o fsdfasdf.cpp ./../jfdjs.hpp

compilerdkfjaösldkacvjfalsdkjföasldfj

./imain.o: ./../.../../imain.cpp ./../.../../imain.hpp
		./../.../../imachein.cpp
		./../.../../imdfeain.cpp
		./../.../../imchbain.cpp
	$(CXX) ./../../../../../src/imain.o dfasdfsdgsdafasdfasdfasdfasdfasdfasdfasdfasdf

compilerdkfjaösldkjfalaesdkjföasldfj
compilerdkfjaösldkjfalsdkjföfdsfaasldfj